from fastapi import APIRouter

router = APIRouter()

@router.post("/")
def run_query(payload: dict):
    question = payload.get("question")

    if not question:
        return {"error": "Question is required"}

    return {
        "question": question,
        "message": "SQL is getting generated by GenAI!!"
    }
